# Workflow to setup ROS2 and test packages

name: setup_ROS2_on_bare_metal
on:
  push:
    branches:
      - main
      # - formatting
  # pull_request:
  #   branches:
  #     - main
env:
  USER: github.actor
jobs:
  build_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [iron]
        packages: [cpp_arief_pubsub, cpp_service_cli]
    steps:
      - name: Check out the current repository to the runner
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_system_dependencies.sh

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_ros.sh

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_package_dependencies.sh

      - name: Running system install dependencies script
        run: .github/workflows/install_system_dependencies.sh "${{ env.USER }}"

      - name: Running install ROS2 script
        run: .github/workflows/install_ros.sh "${{ matrix.distro }}"

      - name: Running install ROS2 extra dependencies script
        run: .github/workflows/install_package_dependencies.sh "${{ matrix.distro }}"

      - name: Build sources
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/ros/iron/setup.bash
          colcon build

      - name: Test packages
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/ros/iron/setup.bash
          colcon test
