# Workflow to test using open-source ros-tooling

name: Setup ROS2 from actions
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  USER: github.actor
jobs:
  setup_ros:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro: [iron, rolling]
    steps:
      - name: Check out the current repository to the runner
        uses: actions/checkout@v4

      - name: Setup ROS2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{matrix.distro}}

      - name: Build ROS2 packages from repo
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/ros/${{matrix.distro}}/setup.bash
          colcon build

      - name: Test ROS2 packages from repo
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/ros/${{matrix.distro}}/setup.bash
          colcon test --event-handler=console_direct+
