# Workflow to setup ROS2 and test packages

name: setup_ROS2
on:
  push:
    branches:
      - main
      - formatting
env:
  USER: github.actor
jobs:
  build_packages:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        packages: [cpp_arief_pubsub]
    steps:
      - name: Check out the current repository to the runner
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_system_dependencies.sh

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_ros.sh

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_package_dependencies.sh

      - name: Running system install dependencies script
        run: .github/workflows/install_system_dependencies.sh "${{ env.USER }}"

      - name: Running install ROS2 script
        run: .github/workflows/install_ros.sh "${{ env.USER }}"

      - name: Running install ROS2 extra dependencies script
        run: .github/workflows/install_package_dependencies.sh "${{ env.USER }}"
      
      - name: Build sources
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/ros/iron/setup.bash
          colcon build

      - name: Test packages
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/ros/iron/setup.bash
          colcon test --packages-select ${{ matrix.packages }}