# Workflow to setup ROS2 and test packages

name: setup_ROS2
on: [push]
env:
  USER: github.actor
jobs:
  install_ROS2_iron:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repository to the runner
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_dependencies.sh

      - name: Running install_dependencies script
        run: .github/workflows/install_dependencies.sh "${{ env.USER }}"

      - name: Installing ROS2-iron
        run: sudo apt install ros-iron-desktop

      - name: Initialise the environment file and check for ROS2
        run: source /opt/ros/iron/setup.bash && ros2 run --help
        
      - name: Success Message
        run: echo "$GITHUB_ACTOR successfully installed ROS2-iron in system"

  build:
    runs-on: ubuntu-latest
    needs: install_ROS2_iron
    steps:
      - name: Source ROS2 Iron (underlay)
        run: source /opt/ros/iron/setup.bash

      - name: Check colcon and rosdep version
        run: which colcon && which rosdep

      - name: Get to workspace directory
        run: cd 

      - name: Update all ROS dependencies using rosdep
        run: rosdep install -i --from-path src --rosdistro iron -y
      
      - name: Build sources
        run: colcon build

      - name: Source ROS2 overlay
        run: source install/setup.bash