# Workflow to setup ROS2 and test packages

name: setup_ROS2
on:
  push:
    branches:
      - formatting
env:
  USER: github.actor
jobs:
  install_ROS2_iron:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the current repository to the runner
        uses: actions/checkout@v4

      - name: Make the script files executable
        run: chmod +x .github/workflows/install_dependencies.sh

      - name: Running install_dependencies script
        run: .github/workflows/install_dependencies.sh "${{ env.USER }}"

      - name: Installing ROS2-iron
        run: sudo apt install ros-iron-desktop

      - name: Initialise the environment file and check for ROS2
        run: source /opt/ros/iron/setup.bash && ros2 run --help
        
      - name: Success Message
        run: echo "$GITHUB_ACTOR successfully installed ROS2-iron in system"

      - name: Install colcon
        run: sudo apt-get update && sudo apt-get install python3-colcon-common-extensions

      - name: Check colcon and rosdep version
        run: which colcon && which rosdep
      
      - name: Initialise and update rosdep
        run: sudo rosdep init && rosdep update

      - name: Install all ROS dependencies using rosdep
        run: rosdep install -i --from-path src --rosdistro iron -y
      
      - name: Build sources
        run: |
          cd $GITHUB_WORKSPACE
          source /opt/ros/iron/setup.bash
          colcon build

  build_run_publisher:
    runs-on: ubuntu-latest
    needs: install_ROS2_iron
    steps:
      - name: Check out the current repository to the runner
        uses: actions/checkout@v4

      - name: Source overlay
        run: |
          cd $GITHUB_WORKSPACE
          source install/setup.bash
          
      - name: Run Publisher
        run: |
          ros2 run cpp_arief_pubsub talker

  build_run_subscriber:
    runs-on: ubuntu-latest
    needs: install_ROS2_iron
    steps:
      - name: Check out the current repository to the runner
        uses: actions/checkout@v4
        
      - name: Source overlay
        run: |
          cd $GITHUB_WORKSPACE
          source install/setup.bash

      - name: Run Publisher
        run: |
          ros2 run cpp_arief_pubsub listener
